'use strict';

const { OPCODES } = require('../bytecode/opcodes');
const { NameGenerator } = require('../utils/names');
const { randInt } = require('../utils/rng');

function luaStringLiteral(s) {
  // Only used for a handful of internal (non-secret) plumbing strings.
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n') + '"';
}

function protoToLua(p) {
  const w = '{' + p.words.flat().join(',') + '}';
  const k = '{' + p.constants.map(c => {
    if (c.t === 0) return `{0,${c.v}}`;
    return `{1,{${c.v.join(',')}}}`;
  }).join(',') + '}';
  const sub = '{' + p.protos.map(protoToLua).join(',') + '}';
  const u = '{' + p.upvals.map(u => `{${u[0]},${u[1]}}`).join(',') + '}';
  return `{${p.numParams},${p.isVararg},${w},${k},${sub},${u}}`;
}

function checksumOf(p) {
  let sum = 0;
  for (const w of p.words) for (const f of w) sum = (sum + f) % 2147483647;
  for (const sub of p.protos) sum = sum + checksumOf(sub);
  return sum;
}

// Builds the complete output.lua source for one compiled+serialized program.
function generateVM(serializedProgram, opmap, options) {
  const rng = options.rng;
  const names = new NameGenerator(rng, { confusable: options.confusable });
  const N = {}; // internal identifier pool
  const need = [
    'bxor', 'decodeField', 'decodeOp', 'decodeStr', 'strCache', 'DATA', 'CK',
    'runProto', 'callValue', 'newClosure', 'truthy', 'RK', 'H', 'mkFrame',
    'XORK', 'ADDK', 'JB', 'SXK', 'SKS', 'NKO', 'RKM', 'checksum', 'walkSum',
    'main', 'ENVT', 'unpackR',
  ];
  for (const n of need) N[n] = names.next();

  const opcodeHandlers = OPCODES.map((name, idx) => generateHandler(name, idx, N)).join('\n');
  const opDispatchEntries = OPCODES.map((name, idx) =>
    `${N.H}[${opmap.encodeOf[idx]}]=${'op_' + name}`).join('\n');

  const dataLiteral = protoToLua(serializedProgram);
  const checksum = checksumOf(serializedProgram);

  return `-- Generated by VM Obfuscator. Do not edit by hand.
local ${N.XORK}, ${N.ADDK}, ${N.JB} = ${opmap.xorKey}, ${opmap.addKey}, ${opmap.jumpBias}
local ${N.SXK}, ${N.SKS}, ${N.NKO} = ${opmap.strXorKey}, ${opmap.strKeyStep}, ${opmap.numKeyOffset}
local ${N.RKM} = 1073741824

local function ${N.bxor}(a, b)
  local r, p = 0, 1
  while a > 0 or b > 0 do
    local abit, bbit = a % 2, b % 2
    if abit ~= bbit then r = r + p end
    a = (a - abit) / 2
    b = (b - bbit) / 2
    p = p * 2
  end
  return r
end

local function ${N.decodeField}(enc)
  local x = (enc - ${N.ADDK}) % 4294967296
  if x < 0 then x = x + 4294967296 end
  return ${N.bxor}(x, ${N.XORK})
end

${N.strCache} = {}
local function ${N.decodeStr}(bytes)
  local out = {}
  for i = 1, #bytes do
    local key = (${N.SXK} + (i - 1) * ${N.SKS}) % 256
    out[i] = string.char(${N.bxor}(bytes[i], key))
  end
  return table.concat(out)
end

local function ${N.RK}(frame, v)
  if v >= ${N.RKM} then
    return frame.k[v - ${N.RKM} + 1]
  end
  return frame.r[v + 1]
end

local function ${N.truthy}(v) return v ~= nil and v ~= false end

${N.ENVT} = _G

${opcodeHandlers}

local ${N.H} = {}
${opDispatchEntries}

-- constant-pool resolver: decodes numbers immediately (cheap), and lazily
-- decodes + memoizes strings only the first time each one is actually used.
local function resolveConst(protoConsts, i, cache)
  local c = cache[i]
  if c ~= nil then return c end
  local raw = protoConsts[i]
  local v
  if (raw[1] == 0) then
    v = raw[2] - ${N.NKO}
  elseif raw[1] == 2 then
    v = raw[2]
  else
    v = ${N.decodeStr}(raw[2])
  end
  cache[i] = v
  return v
end

local function ${N.mkFrame}(protoData, upvals, args, nargs)
  local numParams, isVararg, words, kdata = protoData[1], protoData[2], protoData[3], protoData[4]
  local r, kcache = {}, {}
  for i = 1, numParams do r[i] = args[i] end
  local varargs, nva = {}, 0
  if isVararg == 1 and nargs > numParams then
    nva = nargs - numParams
    for i = 1, nva do varargs[i] = args[numParams + i] end
  end
  return {
    p = protoData, r = r, u = upvals,
    k = setmetatable({}, { __index = function(_, i) return resolveConst(kdata, i, kcache) end }),
    va = varargs, nva = nva, words = words, subprotos = protoData[5], upmeta = protoData[6],
  }
end

function ${N.runProto}(protoData, upvals, args, nargs)
  local frame = ${N.mkFrame}(protoData, upvals, args, nargs)
  local words = frame.words
  local pc = 1
  local top = 0
  while true do
    local base = (pc - 1) * 4
    local opEnc = ${N.decodeField}(words[base + 1])
    local a = ${N.decodeField}(words[base + 2])
    local b = ${N.decodeField}(words[base + 3])
    local c = ${N.decodeField}(words[base + 4])
    pc = pc + 1
    local handler = ${N.H}[opEnc]
    local signal, sa, sb = handler(frame, a, b, c, pc, top)
    if signal == 1 then -- jump
      pc = sa
    elseif signal == 2 then -- return
      return sa, sb
    elseif signal == 3 then -- top changed
      top = sa
    end
  end
end

function ${N.callValue}(fn, args, nargs)
  if type(fn) == 'table' and fn.__vmclosure then
    local results, n = ${N.runProto}(fn.proto, fn.upvals, args, nargs)
    return results or {}, n or 0
  elseif type(fn) == 'function' then
    local packed = table.pack(fn(table.unpack(args, 1, nargs)))
    local n = packed.n
    packed.n = nil
    return packed, n
  else
    local mt = getmetatable(fn)
    if mt and mt.__call then
      local nargs2 = {}
      nargs2[1] = fn
      for i = 1, nargs do nargs2[i + 1] = args[i] end
      return ${N.callValue}(mt.__call, nargs2, nargs + 1)
    end
    error('attempt to call a ' .. type(fn) .. ' value')
  end
end

function ${N.newClosure}(subprotoData, frame)
  local upmeta = subprotoData[6]
  local ups = {}
  for i = 1, #upmeta do
    local m = upmeta[i]
    if m[1] == 1 then
      ups[i] = frame.r[m[2] + 1]
    else
      ups[i] = frame.u[m[2] + 1]
    end
  end
  return { __vmclosure = true, proto = subprotoData, upvals = ups }
end

local ${N.checksum} = ${checksum}
local function ${N.walkSum}(protoData)
  local sum = 0
  local words = protoData[3]
  for i = 1, #words do sum = (sum + words[i]) % 2147483647 end
  local subs = protoData[5]
  for i = 1, #subs do sum = sum + ${N.walkSum}(subs[i]) end
  return sum
end

local ${N.DATA} = ${dataLiteral}

local function ${N.main}(...)
${options.antiTamper !== false ? `  if ${N.walkSum}(${N.DATA}) ~= ${N.checksum} then
    error('integrity check failed: bytecode has been modified')
  end
` : ''}${options.opaque ? opaquePredicateBlock(rng, names) : ''}  local args = { ... }
  local results, n = ${N.runProto}(${N.DATA}, {}, args, select('#', ...))
  return table.unpack(results or {}, 1, n or 0)
end

return ${N.main}(...)
`;
}

// Build-time-true, runtime-checked condition that adds a small amount of
// superficial branch noise around the entry point without touching the
// actual instruction stream (so it can never desync from the bytecode).
function opaquePredicateBlock(rng, names) {
  const p = randInt(rng, 2, 97); // small prime-ish modulus
  const x = randInt(rng, 1000, 99999);
  const y = randInt(rng, 1000, 99999);
  const lhs = (x * x - y * y) % p;
  const rhs = ((x - y) * (x + y)) % p;
  const v1 = names.next();
  const v2 = names.next();
  return `  local ${v1}, ${v2} = ${x}, ${y}
  if ((${v1} * ${v1} - ${v2} * ${v2}) % ${p}) ~= (((${v1} - ${v2}) * (${v1} + ${v2})) % ${p}) then
    error('unreachable')
  end
`;
}

function generateHandler(name, idx, N) {
  // Every handler has signature (frame, a, b, c, pc, top) and returns
  // (signal, x, y) where signal: nil=continue, 1=jump-to-x, 2=return(x,y), 3=top<-x
  const R = 'frame.r';
  switch (name) {
    case 'LOADK':
      return `local function op_LOADK(frame, a, b) frame.r[a+1] = frame.k[b+1]; end`;
    case 'LOADBOOL':
      return `local function op_LOADBOOL(frame, a, b) frame.r[a+1] = (b ~= 0); end`;
    case 'LOADNIL':
      return `local function op_LOADNIL(frame, a, b) for i=0,b do frame.r[a+1+i]=nil end end`;
    case 'MOVE':
      return `local function op_MOVE(frame, a, b) frame.r[a+1] = frame.r[b+1]; end`;
    case 'GETGLOBAL':
      return `local function op_GETGLOBAL(frame, a, b) frame.r[a+1] = ${N.ENVT}[frame.k[b+1]]; end`;
    case 'SETGLOBAL':
      return `local function op_SETGLOBAL(frame, a, b) ${N.ENVT}[frame.k[b+1]] = frame.r[a+1]; end`;
    case 'GETUPVAL':
      return `local function op_GETUPVAL(frame, a, b) frame.r[a+1] = frame.u[b+1]; end`;
    case 'SETUPVAL':
      return `local function op_SETUPVAL(frame, a, b) frame.u[b+1] = frame.r[a+1]; end`;
    case 'GETTABLE':
      return `local function op_GETTABLE(frame, a, b, c) frame.r[a+1] = frame.r[b+1][${N.RK}(frame, c)]; end`;
    case 'SETTABLE':
      return `local function op_SETTABLE(frame, a, b, c) frame.r[a+1][${N.RK}(frame, b)] = ${N.RK}(frame, c); end`;
    case 'NEWTABLE':
      return `local function op_NEWTABLE(frame, a) frame.r[a+1] = {}; end`;
    case 'SELF':
      return `local function op_SELF(frame, a, b, c)
  local obj = frame.r[b+1]
  frame.r[a+2] = obj
  frame.r[a+1] = obj[${N.RK}(frame, c)]
end`;
    case 'ADD': return arith('ADD', '+', N);
    case 'SUB': return arith('SUB', '-', N);
    case 'MUL': return arith('MUL', '*', N);
    case 'DIV': return arith('DIV', '/', N);
    case 'MOD': return arith('MOD', '%', N);
    case 'POW': return arith('POW', '^', N);
    case 'CONCAT':
      return `local function op_CONCAT(frame, a, b, c)
  local s = frame.r[b+1]
  for i = b+2, c+1 do s = s .. frame.r[i] end
  frame.r[a+1] = s
end`;
    case 'UNM':
      return `local function op_UNM(frame, a, b) frame.r[a+1] = -frame.r[b+1]; end`;
    case 'NOT':
      return `local function op_NOT(frame, a, b) frame.r[a+1] = not ${N.truthy}(frame.r[b+1]); end`;
    case 'LEN':
      return `local function op_LEN(frame, a, b) frame.r[a+1] = #frame.r[b+1]; end`;
    case 'JMP':
      return `local function op_JMP(frame, a, b, c, pc) return 1, pc + (b - ${N.JB}); end`;
    case 'EQ':
      return `local function op_EQ(frame, a, b, c, pc)
  if ((${N.RK}(frame, b) == ${N.RK}(frame, c)) == (a ~= 0)) then return 1, pc + 1 end
end`;
    case 'LT':
      return `local function op_LT(frame, a, b, c, pc)
  if ((${N.RK}(frame, b) < ${N.RK}(frame, c)) == (a ~= 0)) then return 1, pc + 1 end
end`;
    case 'LE':
      return `local function op_LE(frame, a, b, c, pc)
  if ((${N.RK}(frame, b) <= ${N.RK}(frame, c)) == (a ~= 0)) then return 1, pc + 1 end
end`;
    case 'TEST':
      return `local function op_TEST(frame, a, b, c, pc)
  if (${N.truthy}(frame.r[a+1]) == (c ~= 0)) then return 1, pc + 1 end
end`;
    case 'CALL':
      return `local function op_CALL(frame, a, b, c, pc, top)
  local nargs
  if b == 0 then nargs = top - a - 1 else nargs = b - 1 end
  local args = {}
  for i = 1, nargs do args[i] = frame.r[a + 1 + i] end
  local results, n = ${N.callValue}(frame.r[a+1], args, nargs)
  if c == 0 then
    for i = 1, n do frame.r[a + i] = results[i] end
    return 3, a + n
  elseif c == 1 then
    -- discard
  else
    for i = 1, c - 1 do frame.r[a + i] = results[i] end
  end
end`;
    case 'RETURN':
      return `local function op_RETURN(frame, a, b, c, pc, top)
  local n
  if b == 0 then n = top - a else n = b - 1 end
  local out = {}
  for i = 1, n do out[i] = frame.r[a + i] end
  return 2, out, n
end`;
    case 'CLOSURE':
      return `local function op_CLOSURE(frame, a, b)
  frame.r[a+1] = ${N.newClosure}(frame.subprotos[b+1], frame)
end`;
    case 'VARARG':
      return `local function op_VARARG(frame, a, b)
  if b == 0 then
    for i = 1, frame.nva do frame.r[a + i] = frame.va[i] end
    return 3, a + frame.nva
  else
    for i = 1, b - 1 do frame.r[a + i] = frame.va[i] end
  end
end`;
    case 'SETLIST':
      return `local function op_SETLIST(frame, a, b, c, pc, top)
  local t = frame.r[a+1]
  local n = top - c
  for i = 0, n - 1 do t[b + i] = frame.r[c + 1 + i] end
end`;
    case 'FORPREP':
      return `local function op_FORPREP(frame, a)
  frame.r[a+1] = tonumber(frame.r[a+1])
  frame.r[a+2] = tonumber(frame.r[a+2])
  frame.r[a+3] = tonumber(frame.r[a+3])
end`;
    case 'FORLOOP':
      return `local function op_FORLOOP(frame, a, b, c, pc)
  local i, limit, step = frame.r[a+1] + frame.r[a+3], frame.r[a+2], frame.r[a+3]
  frame.r[a+1] = i
  if (step > 0 and i <= limit) or (step <= 0 and i >= limit) then
    return 1, pc + (b - ${N.JB})
  end
end`;
    case 'TFORCALL':
      return `local function op_TFORCALL(frame, a, b, c)
  local args = { frame.r[a+2], frame.r[a+3] }
  local results, n = ${N.callValue}(frame.r[a+1], args, 2)
  for i = 1, c do frame.r[a + 3 + i] = results[i] end
end`;
    case 'TFORLOOP':
      return `local function op_TFORLOOP(frame, a, b, c, pc)
  if frame.r[a+2] ~= nil then
    frame.r[a+1] = frame.r[a+2]
    return 1, pc + (b - ${N.JB})
  end
end`;
    case 'HALT':
      return `local function op_HALT() error('halt') end`;
    default:
      throw new Error('no handler generator for ' + name);
  }
}

function arith(name, op, N) {
  return `local function op_${name}(frame, a, b, c) frame.r[a+1] = ${N.RK}(frame, b) ${op} ${N.RK}(frame, c); end`;
}

module.exports = { generateVM };
